In [1]:
# Cosine Similarity between Texts

In [28]:
# Load the documents
d1="Placing Smart WiFi mesh devices around your home creates a mesh network to make sure every device gets the best connection possible."
d2="This is so to do that with the, this is just so this looks like that Is perhaps you talking about our mash based life, right device that and the people to have the right into the process for the parts on the number of having it"
d3="going to go, please describe what you believe this image is customer conveying. Right? Um so I think it's showing you sure this is I think it's just showing you your internet. This is probably like the most um, um and then you have your router here. And then your other router there is part of a mesh network. So nice that and then you different devices that are connected to this, this internet or this network start your business. Just, you know, the Internet being provided through a cable. Um or, or what, but some sort of match why"
d4="initially. Let's move on to the next step 7, please describe in detail what you believe this image is convey. Here we see house, I believe the cloud right here. He's actually representing the cloud. We hear about where we can store data, stuff, pictures, images, pictures, videos, documents, things like that, I believe on, on the cloud. Then we have of, I believe the bars up top on each device we have like 6 or so devices, $78.00 devices. All of them are connected to why fi and this shows the signal. Um, how good does this signal is? The epiphone on the top left, you have a computer in them or t.v. it looks like. And the in the top middle gaming console on the top right. laptop top the bottom left tablet on the bottom right. A security device, it's security device, it seems a doorbell or something. The security camera all connected."
d5="This crime detail what you believe them. It's just conveying all right said this is about setting up a life. I have little hope that to a computer and for life after all the entire house. Now also connect to your um, security as well as outside lies over there. Should be a different door by the russians giving way, I guess that's gonna open up russia or so get some, but my have it loud. Okay. Okay, then I did that step. So next step"
d6="Please describe in detail what you believe this image is, convey his ok. So a picture of a house has many rooms. There are, I think this is conveying, like the kind of Internet connectivity in coverage that you can have in your home with some type of service showing that you can have many devices connected and working on the Internet at the same time different types of devices, tablets, computers, tvs, video games and also like some smart devices, like your camera and stuff. And so I think it's just conveying that this is like a reliable internet provider that can power everything you need and multiple rooms and multiple devices."
d7="Please describe in detail what you believe this image is conveying. Let's see, it appears to be an image of a home, and in my opinion, it looks like um a description of probably a mash router network. So I can see the 3 router splits around the house represented with heck forgot ons connected to various smart devices throughout the house, like a video game console tvs, phones, tablets, computers, doorbell camera. Now the cloud, i'm not certain about so the tears that there's one router connected to a modem and the modem goes to a cloud. I don't know how necessarily cloud storage would play into this."
d8="it now. Please describe in detail what you believe this image is kind of change. This image is showing all of the devices in the home that are connected to why fi, and also the modem is connected to a cloud service here. That's what I'm seeing here,"
d9="please describe detail what you believe this image is conveying, okay? So this looks like, okay, so I see a laptop, a phone. This looks like an access point and access point, another access point, tablet, computer, gaming equipment, rush camera, and ring camera. It looks like all of these are connecting to why fi? These are all access points that they're sort of connecting to. And then those connect to what looks like a modem. And then there's this cloud, i guess maybe this could be, I don't know if this is like sort of trying to explain like a the cloud infrastructure for like a mesh network. Or if this is like conveying, like the Internet service provider providing internet to the modem, which then goes to access or a router which then has multiple access points. So that there's more range for all the devices connected to the network. I want to say this is like, I don't know too much about mesh networks, but I think this looks maybe like I should work. So that's also a"
d10="on to the next. Uh, please describe in detail what you believe this image is conveying what, what it is conveying to me is The sick no. That each device is getting in the home From the end in itself. How much data it could be using or the strength of the and that are object. How much the device itself is giving now And where the weak signals or strong signals and houses are"
d11="is that image. Please describe in detail what you believe this image is conveying. Okay, so to me it looks like we have A computer here. The took to the cloud, right? And it sending off, or this is like a repeater, you know, we have expanded the, so we have a pod expert that, you know, sends a signal to the back of them out. So these, to me look like repeaters. And then of course, this is a cell phone, this is a computer, this is a gaming station of some sort. This is an I pad, this is a laptop. This is like security on the garage. So, and it's all the to the cloud."
d12="Please describe in detail what you believe this image is conveying. Okay, let's see here and make a little bit smaller. Looks to me like it is saying that right internet connection can be reached from the router to that specific spot. But then I also have a way to get connection to video games and my outside security tvs and things. And other rooms for cellphones, computers and laptops, why fi? motion sensors to get into my garage looks like it's telling me that I can get into anything that I need to get to from that Internet connection. Please describe"
d13="on to the next step. Please describe in detail what you believe this image is compelling. Begin the step. It looks like places within my home or someone's home where there would be reception for Internet or high reception for Internet internet will the reception will be the strongest. I'm not sure why that this cloud, i mean I'm thinking new, know the cloud of the cloud out there will be attached to some type of receiver here inside the home and then they'll be places within the home that are Like spots where you the the year um, the service will be picked up and it will be stronger. And yeah, that's what I'm thinking. Next step"
d14="Not looks like it's loaded. Please describe in detail what you believe this image is conveying. Okay, well, it looks like in my opinion, hot spots riders. It's showing you where devices are being connected. Um, as you see in this one, it looks like a cell phone is using this from so it's a picture of a house, a diagram of the house. And it shows each room and what devices connected to the Internet and that room. And then you have these and different ones that are showing an array of different um, signal things which looks to be repeaters. I'm not sure, but I'm guessing this is showing you all the devices that are connected. There's also the garage, it looks to be with a webcam on that that and a ring doorbell and we go back to the house on the bottom floor, we see a tablet and something else that looks like a Y 5, maybe a router repeater that's connected to some sort of outlet, and then a tab looks like a computer. And then up stairs you have a gaming system with t.v. and a cell phone. So I think it's showing you all these devices. But the one thing I see here that I don't understand is it's showing a cloud device is the main input to the home. So I'm not sure what that's supposed to mean. Maybe you're connected to a cloud. I don't"
d15="step. Please describe in detail what you believe this image is conveying. I believe that these are Well, here's a cloud You think we're talking about All of the use. There's different here like the home base for your Internet service or whatever we're talking about. And it connects to these different gonna composite any place um, around the house so that it can reach up there into the different rooms and essentially, and make all of these devices connected to each other so that they can talk to each other. And you can um, control them using maybe one phone or one system"
d16="Please describe in detail. watch what you believe this image is on the Um, I think this image is basically showing many devices that are connected to into the Internet. Reason smart TV, smartphone, tablet, laptop, game console. And it has basically, and there is a, there are some other smart devices like the security cover, as well as his connection to the Internet. So basically, all the devices in this home are connected to the Internet and there are so all the devices are basically connected to the life I in this, in, in this home"
documents = [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16]

In [29]:
d1

'Placing Smart WiFi mesh devices around your home creates a mesh network to make sure every device gets the best connection possible.'

In [30]:
# Preprocessing with nltk
# Normalize by stemming

import nltk, string, numpy

# nltk.download('punkt') # first-time use only

stemmer = nltk.stem.porter.PorterStemmer()
def StemTokens(tokens):
     return [stemmer.stem(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def StemNormalize(text):
     return StemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))


In [31]:
# Normalize by lemmatization

# nltk.download('wordnet') # first-time use only
    
lemmer = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
     return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
     return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [32]:
# Turn text into vectors of term frequency
from sklearn.feature_extraction.text import CountVectorizer
LemVectorizer = CountVectorizer(tokenizer=LemNormalize, stop_words='english')
LemVectorizer.fit_transform(documents)

C:\Users\AD06493\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


<16x236 sparse matrix of type '<class 'numpy.int64'>'
	with 508 stored elements in Compressed Sparse Row format>

In [33]:
print(LemVectorizer.vocabulary_)

{'placing': 138, 'smart': 181, 'wifi': 229, 'mesh': 112, 'device': 47, 'home': 82, 'creates': 42, 'network': 120, 'make': 107, 'sure': 199, 'best': 16, 'connection': 32, 'possible': 142, 'just': 93, 'look': 104, 'like': 101, 'talking': 203, 'mash': 108, 'based': 12, 'life': 100, 'right': 160, 'people': 133, 'process': 145, 'number': 123, 'having': 78, 'going': 72, 'believe': 15, 'image': 87, 'customer': 44, 'conveying': 38, 'um': 218, 'think': 210, 'showing': 177, 'internet': 92, 'probably': 144, 'router': 163, 'nice': 122, 'different': 50, 'connected': 30, 'start': 188, 'business': 18, 'know': 95, 'provided': 146, 'cable': 19, 'sort': 183, 'match': 109, 'initially': 89, 'let': 98, 'step': 190, '7': 3, 'convey': 37, 'house': 85, 'cloud': 25, 'actually': 6, 'representing': 158, 'hear': 79, 'store': 192, 'data': 45, 'stuff': 197, 'picture': 136, 'video': 223, 'document': 51, 'thing': 209, 'bar': 10, '6': 2, '7800': 4, 'fi': 64, 'signal': 179, 'good': 74, 'doe': 52, 'epiphone': 58, 'left'

In [34]:
tf_matrix = LemVectorizer.transform(documents).toarray()
print(tf_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
tf_matrix.shape

(16, 236)

In [36]:
# Calculate idf and turn tf matrix to tf-idf matrix
# Get idf
from sklearn.feature_extraction.text import TfidfTransformer
tfidfTran = TfidfTransformer(norm="l2")
tfidfTran.fit(tf_matrix)
print(tfidfTran.idf_)

[3.14006616 3.14006616 3.14006616 3.14006616 3.14006616 3.14006616
 3.14006616 3.14006616 3.14006616 3.14006616 3.14006616 3.14006616
 3.14006616 3.14006616 3.14006616 1.12516314 3.14006616 3.14006616
 3.14006616 3.14006616 2.22377543 2.73460106 3.14006616 3.14006616
 3.14006616 1.63598877 3.14006616 3.14006616 1.63598877 2.73460106
 1.53062825 3.14006616 2.44691898 3.14006616 3.14006616 2.44691898
 3.14006616 2.73460106 1.43531807 3.14006616 3.14006616 3.14006616
 3.14006616 3.14006616 3.14006616 2.73460106 3.14006616 1.26826399
 3.14006616 3.14006616 2.04145387 3.14006616 3.14006616 2.44691898
 3.14006616 2.44691898 3.14006616 3.14006616 3.14006616 3.14006616
 3.14006616 3.14006616 3.14006616 3.14006616 2.22377543 3.14006616
 3.14006616 2.22377543 2.22377543 2.44691898 3.14006616 2.73460106
 3.14006616 2.73460106 3.14006616 2.73460106 3.14006616 2.44691898
 3.14006616 3.14006616 3.14006616 3.14006616 1.53062825 3.14006616
 3.14006616 1.7537718  2.22377543 1.19415601 3.14006616 3.1400

In [37]:
# Double check
import math
def idf(n,df):
    result = math.log((n+1.0)/(df+1.0)) + 1
    return result
print("The idf for terms that appear in one document: " + str(idf(4,1)))
print("The idf for terms that appear in two documents: " + str(idf(4,2)))

The idf for terms that appear in one document: 1.916290731874155
The idf for terms that appear in two documents: 1.5108256237659907


In [38]:
tfidf_matrix = tfidfTran.transform(tf_matrix)
print(tfidf_matrix.toarray())

[[0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]
 ...
 [0.       0.101065 0.       ... 0.       0.       0.101065]
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]]


In [39]:
cos_similarity_matrix = (tfidf_matrix * tfidf_matrix.T).toarray()
print(cos_similarity_matrix)

[[1.         0.03158252 0.17246931 0.06906319 0.         0.10275617
  0.07760041 0.060132   0.10980804 0.07050326 0.         0.13686959
  0.06054015 0.08736515 0.07084862 0.16875367]
 [0.03158252 1.         0.12416222 0.16936132 0.14950533 0.09703276
  0.08039256 0.01858825 0.09130071 0.02761188 0.12231581 0.09583135
  0.02662873 0.11478315 0.11913951 0.07567052]
 [0.17246931 0.12416222 1.         0.12577993 0.1151459  0.26372608
  0.2290052  0.12675161 0.19586504 0.05036319 0.11146034 0.12834351
  0.1316875  0.27443588 0.23260705 0.21912463]
 [0.06906319 0.16936132 0.12577993 1.         0.12664885 0.27104319
  0.26071304 0.20801067 0.16291669 0.20396673 0.28012592 0.20932088
  0.12220958 0.28780945 0.14891277 0.22238912]
 [0.         0.14950533 0.1151459  0.12664885 1.         0.0653898
  0.04717824 0.03722057 0.07261926 0.08109942 0.09486779 0.16107769
  0.10118989 0.08907968 0.19574001 0.06421292]
 [0.10275617 0.09703276 0.26372608 0.27104319 0.0653898  1.
  0.19591777 0.20039607 0.

In [40]:
# Use TfidfVectorizer instead
from sklearn.feature_extraction.text import TfidfVectorizer
TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()
cos_similarity(documents)


C:\Users\AD06493\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


array([[1.        , 0.03158252, 0.17246931, 0.06906319, 0.        ,
        0.10275617, 0.07760041, 0.060132  , 0.10980804, 0.07050326,
        0.        , 0.13686959, 0.06054015, 0.08736515, 0.07084862,
        0.16875367],
       [0.03158252, 1.        , 0.12416222, 0.16936132, 0.14950533,
        0.09703276, 0.08039256, 0.01858825, 0.09130071, 0.02761188,
        0.12231581, 0.09583135, 0.02662873, 0.11478315, 0.11913951,
        0.07567052],
       [0.17246931, 0.12416222, 1.        , 0.12577993, 0.1151459 ,
        0.26372608, 0.2290052 , 0.12675161, 0.19586504, 0.05036319,
        0.11146034, 0.12834351, 0.1316875 , 0.27443588, 0.23260705,
        0.21912463],
       [0.06906319, 0.16936132, 0.12577993, 1.        , 0.12664885,
        0.27104319, 0.26071304, 0.20801067, 0.16291669, 0.20396673,
        0.28012592, 0.20932088, 0.12220958, 0.28780945, 0.14891277,
        0.22238912],
       [0.        , 0.14950533, 0.1151459 , 0.12664885, 1.        ,
        0.0653898 , 0.04717824, 

In [41]:
import pandas as pd 
df = pd.DataFrame(cos_similarity_matrix)
df

0         1         2         3         4         5         6   \
0   1.000000  0.031583  0.172469  0.069063  0.000000  0.102756  0.077600   
1   0.031583  1.000000  0.124162  0.169361  0.149505  0.097033  0.080393   
2   0.172469  0.124162  1.000000  0.125780  0.115146  0.263726  0.229005   
3   0.069063  0.169361  0.125780  1.000000  0.126649  0.271043  0.260713   
4   0.000000  0.149505  0.115146  0.126649  1.000000  0.065390  0.047178   
5   0.102756  0.097033  0.263726  0.271043  0.065390  1.000000  0.195918   
6   0.077600  0.080393  0.229005  0.260713  0.047178  0.195918  1.000000   
7   0.060132  0.018588  0.126752  0.208011  0.037221  0.200396  0.267482   
8   0.109808  0.091301  0.195865  0.162917  0.072619  0.235551  0.244743   
9   0.070503  0.027612  0.050363  0.203967  0.081099  0.130233  0.087602   
10  0.000000  0.122316  0.111460  0.280126  0.094868  0.132091  0.202401   
11  0.136870  0.095831  0.128344  0.209321  0.161078  0.219544  0.164273   
12  0.060540  0.026629  0.131687  0.122210  0.101190  0.159886  0.158039   
13  0.087365  0.114783  0.274436  0.287809  0.089080  0.298420  0.312996   
14  0.070849  0.119140  0.232607  0.148913  0.195740  0.239739  0.144219   
15  0.168754  0.075671  0.219125  0.222389  0.064213  0.311807  0.182080   

          7         8         9         10        11        12        13  \
0   0.060132  0.109808  0.070503  0.000000  0.136870  0.060540  0.087365   
1   0.018588  0.091301  0.027612  0.122316  0.095831  0.026629  0.114783   
2   0.126752  0.195865  0.050363  0.111460  0.128344  0.131687  0.274436   
3   0.208011  0.162917  0.203967  0.280126  0.209321  0.122210  0.287809   
4   0.037221  0.072619  0.081099  0.094868  0.161078  0.101190  0.089080   
5   0.200396  0.235551  0.130233  0.132091  0.219544  0.159886  0.298420   
6   0.267482  0.244743  0.087602  0.202401  0.164273  0.158039  0.312996   
7   1.000000  0.126235  0.091511  0.087809  0.060969  0.222450  0.317011   
8   0.126235  1.000000  0.032341  0.292831  0.169051  0.120622  0.293159   
9   0.091511  0.032341  1.000000  0.095943  0.034037  0.044599  0.135794   
10  0.087809  0.292831  0.095943  1.000000  0.215205  0.130198  0.345686   
11  0.060969  0.169051  0.034037  0.215205  1.000000  0.096069  0.215061   
12  0.222450  0.120622  0.044599  0.130198  0.096069  1.000000  0.216566   
13  0.317011  0.293159  0.135794  0.345686  0.215061  0.216566  1.000000   
14  0.150693  0.112256  0.121773  0.094585  0.097393  0.203081  0.265509   
15  0.215773  0.098545  0.095640  0.072296  0.182723  0.122762  0.218753   

          14        15  
0   0.070849  0.168754  
1   0.119140  0.075671  
2   0.232607  0.219125  
3   0.148913  0.222389  
4   0.195740  0.064213  
5   0.239739  0.311807  
6   0.144219  0.182080  
7   0.150693  0.215773  
8   0.112256  0.098545  
9   0.121773  0.095640  
10  0.094585  0.072296  
11  0.097393  0.182723  
12  0.203081  0.122762  
13  0.265509  0.218753  
14  1.000000  0.141858  
15  0.141858  1.000000

In [1]:
%cd "C:\Users\Projects\Files"


[WinError 3] The system cannot find the path specified: 'C:\\Users\\Projects\\Files'
C:\Users\AD06493


In [43]:
df.to_csv('similarity_matrix.csv') 